// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1HpjWme-1y6CWiuIFXzLdnV4z7rvbfcM',
    appId: '1:517138091586:web:a71316f9621a43e5a0e7db',
    messagingSenderId: '517138091586',
    projectId: 'flutterfirst-3c4fd',
    authDomain: 'flutterfirst-3c4fd.firebaseapp.com',
    storageBucket: 'flutterfirst-3c4fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQY7KST-My9FuD72Wog5HeItQ50BgNVnQ',
    appId: '1:517138091586:android:436713c480b14c3da0e7db',
    messagingSenderId: '517138091586',
    projectId: 'flutterfirst-3c4fd',
    storageBucket: 'flutterfirst-3c4fd.appspot.com',
  );
}
